Add API Endpoint to congirutation
swinton/insomnia-plugin-github-apps-helper pull request #14
Opened 2019-10-09 19:05 UTC by jules2689

This allows Insomnia to work with non-github.com installations, like GitHub Enterprise or running locally.

This works off of the `github_api_root` provided by https://git.io/github-rest-apis-for-insomnia

2019-10-14 20:48 UTC, swinton requested changes
Thanks for the PR! Happy to merge this if you can accept my suggestion of adding a default value for `GitHub API Root `?

2019-10-14 20:48 UTC, swinton commented on index.js
> +      let { github_app_id: id, github_app_private_key_path: path, github_api_root: githubApiRoot } = context;
Could we add a default here?

```suggestion
      let { github_app_id: id, github_app_private_key_path: path, github_api_root: githubApiRoot = 'https://api.github.com' } = context;
```

2019-10-15 13:38 UTC, jules2689 commented
Done @swinton !

2019-10-16 15:29 UTC, swinton approved these changes

2019-10-16 15:29 UTC, merged